name: 'Create Asana Task'
author: 'Honeycomb'
description: 'Trigger task creation in Asana from Github'

inputs:
  asana-secret: 
    description: 'Asana PAT'
    required: true
  asana-workspace-id:
    description: 'Your Asana Workspace ID'
    required: true
  asana-project-id:
    description: 'Your Asana Project ID'
    required: true
  asana-section-id:
    description: 'Your Asana Section ID (column the task should belong to)'
    required: false
  asana-task-name:
    description: 'Name for Asana task'
    required: true
  asana-task-description:
    description: 'Description for Asana task'
    required: false
  asana-due-date:
    description: 'Date on which Asana task is due (YYYY-MM-DD)'
    required: false
  asana-tags:
    description: 'List of tag IDs to associate with Asana task'
    required: false
  asana-custom-fields:
    description: 'JSON object of custom field IDs and values to associate with Asana task'
    required: false
  

runs:
  using: 'node16'
  main: 'dist/index.js'
